Fixing missing locale-gen command
Error was:

Step 3/15 : RUN locale-gen en_US.UTF-8
 ---> Running in 35c573bc2b79
/bin/sh: 1: locale-gen: not found
ERROR: Service 'app' failed to build: The command '/bin/sh -c locale-gen en_US.UTF-8' returned a non-zero code: 127